name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 0 * * 0"  # every Sunday at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D Profile
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@master
        with:
          username: arunodmanoharaofficial
      - name: Commit & Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m "Generated 3D contribution graph"
          git push